[test.Build]

cmd = "make"
timeout = 60

[test.Help]

cmd = "./202unsold -h"
stdout = """
USAGE
    ./202unsold a b

DESCRIPTION
    a       constant computed from past results
    b       constant computed from past results
"""
stderr = ""

[test."Invalid argument A"]

cmd = "./202unsold a 60"
exit_status = 84

[test."Invalid argument B"]

cmd = "./202unsold 60 b"
exit_status = 84

[test."No arguments"]

cmd = "./202unsold"
exit_status = 84

[test."Not enought arguments"]

cmd = "./202unsold 60"
exit_status = 84

[test."Too low A"]

cmd = "./202unsold 50 60"
exit_status = 84

[test."Too low B"]

cmd = "./202unsold 60 50"
exit_status = 84

[test."60x60"]

cmd = "./202unsold 60 60"
stdout = """
--------------------------------------------------------------------------------
	X=10	X=20	X=30	X=40	X=50	Y law
Y=10	0.111	0.089	0.067	0.044	0.022	0.333
Y=20	0.089	0.071	0.053	0.036	0.018	0.267
Y=30	0.067	0.053	0.040	0.027	0.013	0.200
Y=40	0.044	0.036	0.027	0.018	0.009	0.133
Y=50	0.022	0.018	0.013	0.009	0.004	0.067
X law	0.333	0.267	0.200	0.133	0.067	1.000
--------------------------------------------------------------------------------
z	20	30	40	50	60	70	80	90	100
p(Z=z)	0.111	0.178	0.204	0.196	0.156	0.089	0.044	0.018	0.004
--------------------------------------------------------------------------------
expected value of X:	23.3
variance of X:		155.6
expected value of Y:	23.3
variance of Y:		155.6
expected value of Z:	46.7
variance of Z:		311.1
--------------------------------------------------------------------------------
"""
stderr = ""

[test."60x70"]

cmd = "./202unsold 60 70"
stdout = """
--------------------------------------------------------------------------------
	X=10	X=20	X=30	X=40	X=50	Y law
Y=10	0.100	0.080	0.060	0.040	0.020	0.300
Y=20	0.083	0.067	0.050	0.033	0.017	0.250
Y=30	0.067	0.053	0.040	0.027	0.013	0.200
Y=40	0.050	0.040	0.030	0.020	0.010	0.150
Y=50	0.033	0.027	0.020	0.013	0.007	0.100
X law	0.333	0.267	0.200	0.133	0.067	1.000
--------------------------------------------------------------------------------
z	20	30	40	50	60	70	80	90	100
p(Z=z)	0.100	0.163	0.193	0.193	0.167	0.100	0.053	0.023	0.007
--------------------------------------------------------------------------------
expected value of X:	23.3
variance of X:		155.6
expected value of Y:	25.0
variance of Y:		175.0
expected value of Z:	48.3
variance of Z:		330.6
--------------------------------------------------------------------------------
"""
stderr = ""

[test."80x60"]

cmd = "./202unsold 80 60"
stdout = """
--------------------------------------------------------------------------------
	X=10	X=20	X=30	X=40	X=50	Y law
Y=10	0.093	0.080	0.067	0.053	0.040	0.333
Y=20	0.075	0.064	0.053	0.043	0.032	0.267
Y=30	0.056	0.048	0.040	0.032	0.024	0.200
Y=40	0.037	0.032	0.027	0.021	0.016	0.133
Y=50	0.019	0.016	0.013	0.011	0.008	0.067
X law	0.280	0.240	0.200	0.160	0.120	1.000
--------------------------------------------------------------------------------
z	20	30	40	50	60	70	80	90	100
p(Z=z)	0.093	0.155	0.187	0.192	0.173	0.107	0.059	0.027	0.008
--------------------------------------------------------------------------------
expected value of X:	26.0
variance of X:		184.0
expected value of Y:	23.3
variance of Y:		155.6
expected value of Z:	49.3
variance of Z:		339.6
--------------------------------------------------------------------------------
"""
stderr = ""